name: GitHub Actions Build and Deploy Demo

#触发条件
on:
  push:
    branches:
      - master
#任务
jobs:
  build-and-deploy:
    #服务器环境：最新版Ubuntu
    runs-on: windows-latest
    steps:
    #拉取代码
    - name: Checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: false
    #生成静态文件
    - name: Build
        run: npm install && npm run build

      # 部署到 GitHub Pages

        needs:[build]
        runs-on:ubuntu-latest
        steps:
            -name: Checkout
              use: actions/checkout@v3
            -name:Download Artifacts
              uses:actions/download-artifact@v1
                  with:
                      name: site 
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist